Repository Trond240/Mod_3_V-RAD_APP, pull requests merged in 2020-05, with the labels that each got.

#1 Login page
  package-lock.json
  package.json
  pull_request_template.md
  src/App.js
  src/apiCalls.js
  src/components/LoginPage/loginPage.js
  src/index.js
Labels: enhancement

#2 Login page
  src/App.js
  src/apiCalls.js
  src/components/Areas/areas.css
  src/components/Areas/areas.js
  src/components/AreasContainer/areasContainer.js
  src/components/ListingCard/listingCard.js
  src/components/ListingContainer/listingContainer.js
Labels: enhancement

#3 Information listings now fetch and update the state.
  src/App.js
  src/apiCalls.js
  src/components/AreasContainer/areasContainer.js
  src/components/ListingCard/listingCard.js
  src/components/ListingContainer/listingContainer.js
Labels: enhancement

#5 Fix paths
  src/App.js
  src/apiCalls.js
  src/components/Areas/areas.js
  src/components/AreasContainer/areasContainer.js
Labels: bug, enhancement

#6 Navbar and Container Styling
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/apiCalls.js
  src/components/Areas/areas.css
  src/components/AreasContainer/areasContainer.css
  src/components/AreasContainer/areasContainer.js
  src/components/Detail-Information/detailInformation.js
  src/components/ListingCard/listingCard.js
  src/components/ListingCard/listingCrad.css
  src/components/ListingContainer/listingContainer.css
  src/components/ListingContainer/listingContainer.js
  src/components/ListingDetails/listingDetails.css
  src/components/ListingDetails/listingDetails.js
  src/components/LoginPage/loginPage.css
  src/components/LoginPage/loginPage.js
  src/components/NavBar/navBar.css
  src/components/NavBar/navBar.js
  src/components/loginPage.css
  src/images/packman-background.jpg
  src/index.css
  src/logo.svg
Labels: bug, enhancement

#8 Fix parths to components
  src/App.js
  src/components/ListingCard/listingCard.js
  src/components/ListingContainer/listingContainer.js
Labels: bug
